export { default as HomePage } from "./HomePage";
export { default as ServiceSection } from "./ServiceSection";
export { default as AspirationSection } from "./AspirationSection";
export { default as KeyFocusSection } from "./KeyFocusSection";
export { default as AboutPage } from "./AboutPage";
export { default as HowItWorks } from "./HowItWorks";
export { default as SubscribeSection } from "./SubscribeSection";
export { default as Footer } from "./Footer";
export { default as DiseasesWeTreat } from "./DiseasesWeTreat";